import Header from "./components/Header";
import TopicBar from "./components/TopicBar";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Header />
        <TopicBar />
        {children}
      </body>
    </html>
  );
}
